### ISSUE TITLE
PA Review: Index/Photo Feed

### ISSUE THREAD

**Issue by ck4adventure** [ck2germany/800pics#4]
- [x] Backend: db, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by niartenyaw** [comment]
Looks great!

## Functionality

+ Does what it should!

## Style

- [x] I think the index item should have a different background color than the full background

**Comment by ck4adventure** [comment]
Done!  :)

**Comment by niartenyaw** [comment]
Awesome, looks good! Feel free to close!
