### ISSUE TITLE
PA Review: Profile Page

### ISSUE THREAD

**Issue by ck4adventure** [ck2germany/800pics#5]
- [x] Backend: db, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x]  Presentational Components
- [x]  Styling
- [x]  Smooth, bug-free navigation
- [x]  Adequate and appropriate seeds

**Comment by ck4adventure** [comment]
Aaron: I made some styling changes to the main/index to line it up better with the profile page.

Also, I don't like how the photos don't line up at the bottom of the tiling component on the user profile, but I also don't know what I would do to get around that.

**Comment by niartenyaw** [comment]
Awesome!

## Functionality

Nothing!

## Style

- [x] The background color of the nav, user detail, and photo index are all the same. May want some amount of differentiation
- [ ] What are you using to display the photos like that? masonry? flex-wrap? Depending on what it is, it may not be possible to fix. This could also eventually be turned into infinite scrolling
- [ ] You have a `Loading...` or `One moment please`, this should be a full styled component eventually. You don't necessarily do that now, but it will look much better

**Comment by ck4adventure** [comment]
- [x] I'm using masonry, as long as you are willing to sign off on it, I'll add to the list to find something better later
- [x] a load spinner is also on my list of upgrades

- [x] unless you hate the new colors, I think I'm good? on to the follows buttons....  :)

**Comment by niartenyaw** [comment]
That's fine with me!
